version: '3.9'

services:
  qnode01_app:
    image: smartquail/qnode01_app:latest
    environment:
      - PORT=9000
    env_file:
      - .env_dev 
    depends_on:
      - smartquaildb
    expose:
    - 9000
    ports:
      - "9000:9000"
    volumes:
      - static-data-qnode01:/qnode0.1_app/qnode01_app/staticfiles
      - static-data-qnode01:/qnode0.1_app/qnode01_app/media
   # command: sh -c "chmod +x /scripts/migrations.sh && sh /scripts/migrations.sh && sh /scripts/run.sh"
    networks: 
      - lansmartquail

  smartquaildb:
    image: postgres:13-alpine
    restart: always
    command: -p 5432
    env_file:
      - .env_dev
    ports:
      - "5432:5432"
    expose:
     - 5432
    volumes:
      - smartquaildb_data:/var/lib/postgresql/data/
    networks: 
      - lansmartquail
      

  qnode0_proxy:
    image: smartquail/qnode01_nginx:dev
    restart: always
    ports:
      - "80:80"
    depends_on:
      - qnode01_app
    volumes: 
      - static-data-qnode01:/qnode0.1_app/qnode01_app/staticfiles
      - static-data-qnode01:/qnode0.1_app/qnode01_app/media
    networks: 
      - lansmartquail
   

  redis:
    image: redis:3.0
    restart: always
    expose:
      - 6379
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    entrypoint: redis-server --appendonly yes --port 6379
    networks: 
      - lansmartquail

volumes:
  smartquaildb_data:
  redis_data:
  static-data-qnode01:

networks: 
   lansmartquail:
       driver: bridge