version: '3.9'

services:
  qnode01_app:
    image: smartquail/qnode01_app:latest
    environment:
      - PORT=9000
    env_file:
      - .env_prod 
    depends_on:
      - smartquaildb
    expose:
    - 9000
    ports:
      - "9000:9000"
    volumes:
      - static-data-qnode0:/qnode0.0_app/qnode0_app/staticfiles
      - static-data-qnode0:/qnode0.0_app/qnode0_app/media
   # command: sh -c "chmod +x /scripts/migrations.sh && sh /scripts/migrations.sh && sh /scripts/run.sh"

  smartquaildb:
    image: postgres:13-alpine
    restart: always
    command: -p 5432
    env_file:
      - .env_prod 
    ports:
      - "5432:5432"
    expose:
     - 5432
    volumes:
      - smartquaildb_data:/var/lib/postgresql/data/
      

  qnode01_proxy:
    image: smartquail/qnode01_nginx:prod
    restart: always
    env_file:
      - .env_prod 
    ports:
    - "80:80"
    - "443:443"
    depends_on:
    - qnode01_app
    volumes: 
    - nginx_conf:/etc/nginx/sites
    - nginx_ssl:/etc/nginx/ssl
    - letsencrypt_certs:/etc/letsencrypt
    - certbot_acme_challenge:/var/www/certbot
    - static-data-qnode0:/qnode0.0_app/qnode0_app/staticfiles
    - static-data-qnode0:/qnode0.0_app/qnode0_app/media

  certbot:
    image: smartquail/qnode01_certbot:0.1
    env_file:
      - .env_prod 
    volumes:
      - letsencrypt_certs:/etc/letsencrypt
      - certbot_acme_challenge:/var/www/certbot
    depends_on:
      - qnode01_proxy

  cron:
    image: smartquail/qnode01_cron:0.1
    environment:
      COMPOSE_PROJECT_NAME: "${COMPOSE_PROJECT_NAME}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/workdir:ro
    depends_on:
      - qnode01_proxy
      - certbot
   

  redis:
    image: redis:3.0
    restart: always
    expose:
      - 6379
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    entrypoint: redis-server --appendonly yes --port 6379
  
volumes:
  smartquaildb_data:
  redis_data:
  static-data-qnode0:
  nginx_conf:
  nginx_ssl:
  certbot_acme_challenge:
  letsencrypt_certs:
  